### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by LightBlueCube** [x3Karma/Admin-Abuse-Mod#9]
so first, my english very bad
when player use command "spawntitan" and "spawnviper"
mod doesn't check player isn't admin
I fix it (maybe)
[spawncmd.zip](https://github.com/x3Karma/Admin-Abuse-Mod/files/9752779/spawncmd.zip)

**Comment by LightBlueCube** [comment]
https://forums.northstar.cool/thread/12

**Comment by x3Karma** [comment]
谢谢 lol

These two commands was my very first mod so i forgot to check for admin permissions.
